language: node_js
node_js:
- 0.12.2
before_install:
- openssl aes-256-cbc -K $encrypted_1b2e8922f766_key -iv $encrypted_1b2e8922f766_iv
  -in certs/key.pem.enc -out certs/key.pem -d
- npm install -g gulp
script: gulp
deploy:
  provider: releases
  api_key:
    secure: cTWZs3Q+cf9+s10g8isDHWUIE+2cx1Tz1WMG5CMUuCrwcflZqk9GTcYdATljZrUHaKjL57xWPFjKH8YXBykET1RK93Tcse5VBpo5vGfsMO+5zzSw7mFw3vFg/BO3PrOYtwbKIFb93qkk8KHGNT8OIinkokf0hgY3IktO5kzJlsnqH2m6nCpjOi6zF1EsTzRJt1Bz1QNOJq3E2vD0qEklezexBjAsUoMxGnumQWG4xCNcKZvjqCVW8Y9TKGFRe5G38PVYttaJktOmCykx97lcsZ5ohdp3mJx9AK2ruQmyRfY/kOSgIL63dq5bN91WczKRYy/kO/6IIzoFUxDzjBPP7L+QzLi1PupMJ9WzoJ1+8ibOaZUITp7U19Zo6SeN4M0zOfR7TB56zOREmx9XbG9TUJPu3YBJcXi6k25zf4e2DhZaQ2d9hSlIGNK5oGaZdPCI+GSkqdphUx4U5j37SnouTvmBUv1Stljs9J9Qcs2HkAGEYCAyjXzYMd+PETrm9MbLWclFW7GjMqAlsXf3DKWLEkc8e4X5e8LzFflNMCbGNWpp/RxGOD4JCD1wJxPUANHYxe6fn6k2jy9nxHNQk5hQz4E05KR2zI6c7oslmaAYdoN6ejAfPXuUzfgCw1bE0a9G5d5ztOuYkQkMBCL5Rhi9cUAcpV12PFoQAcZS8nM3KJQ=
  file: build/CssPath.crx
  on:
    tags:true
	all_branches: true
  overwrite: true
  skip_cleanup: true
